# Generated by Django 5.0.2 on 2024-02-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                default= 0,
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.User',
            ),
        ),
    ]
