# Generated by Django 5.0.2 on 2024-02-27 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0003_alter_author_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="password",
        ),
        migrations.RemoveField(
            model_name="author",
            name="username",
        ),
    ]
