# Generated by Django 5.0.2 on 2024-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0004_remove_author_password_remove_author_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="date",
            field=models.DateField(),
        ),
    ]
